export const POPULATION_UNIT = 100000;

export const INVALID_GEO_NAMES = [
  'Anguilla',
  'Aruba',
  'Bermuda',
  'British Virgin Islands',
  'Caribbean Netherlands',
  'Cayman Islands',
  'Channel Islands',
  'Curaçao',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'French Guiana',
  'French Polynesia',
  'Gibraltar',
  'Greenland',
  'Guadeloupe',
  'Holy See (Vatican City State)',
  'Hong Kong',
  'Isle of Man',
  'Macao',
  'Martinique',
  'Mayotte',
  'Montserrat',
  'Myanmar',
  'New Caledonia',
  'Palestine',
  'Réunion',
  'Saint Martin',
  'Saint Pierre Miquelon',
  'Sint Maarten',
  'St. Barth',
  'Turks and Caicos Islands',
  'Wallis and Futuna',
  'Western Sahara',
];
